### ISSUE TITLE
 Avoid MVCC_READ_CONFLICT when adding signatures 

### ISSUE THREAD

**Issue by jonathan-m-hamilton** [hyperledger-labs/blockchain-integration-framework#11]
**Current state** 
Signatures on Fabric are stored in a single key-value store and will cause MVCC_READ_CONFLICT if modified concurrently  

**Desired state** 
Change on-chain storage and according functions to avoid conflicts and allow for concurrent modification of different signatures.

**Comment by denis-yu-glotov** [comment]
My attempts commits are here. https://github.com/denis-yu-glotov/blockchain-integration-framework/tree/denis/concurrency.
Attempting to test it, I hit https://github.com/hyperledger-labs/blockchain-integration-framework/issues/56#issuecomment-557647247 and was trying to fix it myself (actually, I discovered that issue a day later). 
Eventually, I tested Quorum network (both the version 2.1.1 that we are using now and latest 2.3.0) and I see that is unable to make transactions through websockets. So I agree with Peter, we need to switch back to http, because
* http is always used in the wild (I have never seen anyone using websockets on github projects),
* we will not have this `web3_timestamp_fix.patch` mess anymore,
* the reason why we used ws from the beginning was that our early developers believed ws is more advanced to http and it allows to pass more parameters in a single call. I argued that ws is never used in public. And now it is just broken.
