### ISSUE TITLE
Add Scenarios to Travis CI

### ISSUE THREAD

**Issue by jonathan-m-hamilton** [hyperledger-labs/blockchain-integration-framework#34]

**Comment by petermetz** [comment]
#72

**Comment by denis-yu-glotov** [comment]
Re-opening to add Corda scenarios

**Comment by denis-yu-glotov** [comment]
https://github.com/hyperledger-labs/blockchain-integration-framework/pull/84#issuecomment-565117066

**Comment by denis-yu-glotov** [comment]
I also tried Azure pipelines (https://github.com/denis-yu-glotov/blockchain-integration-framework/tree/denis/azure-pipelines) but it turned out that their VM is fixed to standard 2 vCPU and 7 GiB memory: https://stackoverflow.com/questions/59530127/how-can-i-specify-vm-properties-cpu-memory-for-azure-pipelines. This is not enough for our scenarios.
